language: php
php:
  - 7.3.0
install: composer install
services:
  - postgresql
before_script:
  - cp .env.travis .env
  - psql -c 'create database urlshortener;' -U postgres
  - psql -c "CREATE USER homestead WITH PASSWORD 'secret';" -U postgres
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
script:
  - make generate-key
  - make migration
  - make test
  - make lint
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
